import { accuracySpread } from '../src/accuracy.js';
import { exposedHit } from './body-fixtures.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import {applyInjury} from '../src/injury.js';
import {Effects} from '../src/effects.js';
import {updateEnemyFire,enemyShotAngle} from '../src/enemy-fire.js';
test('support arm drops alone, keeps shooting with wobble, then trigger arm drops rifle once',()=>{
 const e={hp:100,x:300,y:300,angle:0,aimAngle:0,timer:0,aimDuration:.1,burstCount:3,burstInterval:.1,shotSpread:.014,damage:20,bulletSpeed:1000,fireInterval:1},fx=new Effects();
 exposedHit(e,'leftArm');fx.detach(e,'arm',0);
 assert.equal(e.armsDisabled,false);assert.equal(e.aimImpaired,true);
 assert.deepEqual(fx.items.items.map(e=>e.kind),['droppedArm']);
 const shots=[];for(let i=0;i<10;i++)updateEnemyFire(e,.05,{x:600,y:300},(x,y,a)=>shots.push(a),true,()=>1);
 assert.equal(shots.length,3);assert.ok(shots.some(a=>Math.abs(a)>.04));
 const healthy={...e,body:undefined,aimImpaired:false};
 assert.ok(accuracySpread(e)>accuracySpread(healthy));
 exposedHit(e,'rightArm');fx.detach(e,'arm',0);
 assert.ok(e.armsDisabled);assert.equal(e.aimImpaired,false);
 assert.equal(fx.items.items.filter(e=>e.kind==='droppedRifle').length,1);
 for(let i=0;i<10;i++)updateEnemyFire(e,.1,{x:600,y:300},()=>shots.push(99));
 assert.equal(shots.length,3);
});
